# Generated by Django 5.0.1 on 2024-01-27 07:56

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('socialmedia_api', '0002_alter_profile_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='comment',
            name='user',
        ),
        migrations.RemoveField(
            model_name='post',
            name='user',
        ),
        migrations.RemoveField(
            model_name='reaction',
            name='user',
        ),
        migrations.AddField(
            model_name='comment',
            name='profile',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='socialmedia_api.profile'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='post',
            name='profile',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='posts', to='socialmedia_api.profile'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='reaction',
            name='Profile',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='socialmedia_api.profile'),
            preserve_default=False,
        ),
    ]
