# Generated by Django 5.0.1 on 2024-01-27 08:15

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('socialmedia_api', '0003_remove_comment_user_remove_post_user_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='profile',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='socialmedia_api.profile'),
        ),
        migrations.AlterField(
            model_name='follower',
            name='follower_id',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='socialmedia_api.profile'),
        ),
        migrations.AlterField(
            model_name='follower',
            name='user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='post',
            name='profile',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='socialmedia_api.profile'),
        ),
        migrations.AlterField(
            model_name='reaction',
            name='Profile',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='socialmedia_api.profile'),
        ),
        migrations.AlterField(
            model_name='reaction',
            name='post',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='socialmedia_api.post'),
        ),
    ]
