# Generated by Django 5.0.1 on 2024-01-27 14:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('socialmedia_api', '0004_alter_comment_profile_alter_follower_follower_id_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='media',
            field=models.ImageField(upload_to='images'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='avatar',
            field=models.ImageField(upload_to='images'),
        ),
    ]
