# Generated by Django 5.0.1 on 2024-01-27 15:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('socialmedia_api', '0005_alter_post_media_alter_profile_avatar'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='media',
            field=models.ImageField(null=True, upload_to='images'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='avatar',
            field=models.ImageField(null=True, upload_to='images'),
        ),
    ]
