# Generated by Django 5.0.1 on 2024-01-27 21:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('socialmedia_api', '0006_alter_post_media_alter_profile_avatar'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='phone_number',
            field=models.CharField(max_length=20, null=True),
        ),
    ]
